app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame
from source.video_detector import print_notif

import json
import time
import os
from datetime import date
from datetime import timedelta
from time import gmtime, strftime

counter = 100
statusNotif = "nothing"

@main_bp.route("/")
def home_page():
    # flash("Not So OK", 'error')
    # gg = show_notif()
    # print(gg)
    return render_template("home_page.html")

@main_bp.route("/datareview")
def chart():
    # Get today's date
  today = date.today()
  print("Today is: ", today)
    
  # Yesterday date
  # yesterday = today - timedelta(days = 1)
  # print("Yesterday was: ", yesterday)

  pathDefault = "G:/skripsi/MaskDetector/app/static/gambar_wajah/"

  checkFolderToday = os.path.isdir(pathDefault + str(today))
  print(checkFolderToday)
  if checkFolderToday == True:
    countWithMaskToday = len(os.listdir(pathDefault + str(today) + "/withMask"))
    countNoMaskToday = len(os.listdir(pathDefault + str(today) + "/noMask"))
  else:
    countWithMaskToday = 0
    countNoMaskToday = 0
  print(countWithMaskToday)
  print(countNoMaskToday)

  my_list = os.listdir(pathDefault)
  countListDir = len(my_list)
  print(my_list)
  print(countListDir)
  countWithMaskAll = []
  countNoMaskAll = []
  if countListDir > 0:
    for FolderX in my_list:
      countWithMaskAll.append(int(len(os.listdir(pathDefault + str(FolderX) + "/withMask"))))
      countNoMaskAll.append(int(len(os.listdir(pathDefault + str(FolderX) + "/noMask"))))
  else:
    countWithMaskAll = []
    countNoMaskAll = []
  
  print(countWithMaskAll)
  print(countNoMaskAll)
  legend = 'All Day'
  labels = ["With Mask", "No Mask"]
  labels2 = my_list

  values = countWithMaskToday
  valuesNoMask = countNoMaskToday
  values2 = countWithMaskAll
  values3 = countNoMaskAll  
  return render_template('datareview.html', values=values, valuesNoMask=valuesNoMask, values2=values2, values3=values3, labels=labels, labels2=labels2, legend=legend)

def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = detect_mask_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')

@main_bp.route("/listen")
def listen():

  def respond_to_client():
    while True:
      global counter
      global statusNotif
      statusNotif = print_notif()
    #   print(statusNotif)
      color = "white"
    #   with open("color.txt", "r") as f:
    #     color = f.read()
    #     print("******************")
      if(color == "white"):
        # print(counter)
        # counter += 1
        _data = json.dumps({"color":color, "counter":statusNotif})
        yield f"id: 1\ndata: {_data}\nevent: online\n\n"
      time.sleep(0.5)
  return Response(respond_to_client(), mimetype='text/event-stream')

def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_mask_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

app/templates/data_review.html
{% extends "template.html" %}
{% block content %}
<div class="container pt-4">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <center>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </center>
            </div>
        </div>
        <!-- <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div> -->
        <hr>
        <div class="row mb-3">
            <p class="d-flex mx-auto lead" style="color: #031b19;"><strong>please, stay safe and wear a mask ❤</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $('#live').attr('class', 'nav-item');
        $('#data-review').attr('class', 'nav-item active');
        document.querySelector("#counter").innerText = "2";
    })
    // Global parameters:
    // do not resize the chart canvas when its container does (keep at 600x400px)
    Chart.defaults.global.responsive = false;
    // get chart canvas
    var ctx = document.getElementById("myChart").getContext("2d");
    // create the chart using the chart canvas
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for item in labels %}
                "{{item}}",
                {% endfor %}],
        datasets: [{
            label: '{{ legend }}',
            data: [{% for item in values %}
            {{item}},
            {% endfor %}],
            backgroundColor: [
                'rgba(5, 171, 154, 0.5)',
                'rgba(255, 99, 132, 0.5)'
            ],
            borderColor: [
                'rgba(5, 171, 154, 1)',
                'rgba(255, 99, 132, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
        yAxes: [{
            ticks: {
                beginAtZero: true
            }
        }]
    }
    }
});
</script>
{% endblock %}

app/templates/data_review_old.html
{% extends "template.html" %}
{% block content %}
<div class="container pt-4">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <center>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </center>
            </div>
        </div>
        <!-- <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div> -->
        <hr>
        <div class="row mb-3">
            <p class="d-flex mx-auto lead" style="color: #031b19;"><strong>please, stay safe and wear a mask ❤</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $('#live').attr('class', 'nav-item');
        $('#data-review').attr('class', 'nav-item active');
        document.querySelector("#counter").innerText = "2";
    })
    // Global parameters:
    // do not resize the chart canvas when its container does (keep at 600x400px)
    Chart.defaults.global.responsive = false;
    // get chart canvas
    var ctx = document.getElementById("myChart").getContext("2d");
    // create the chart using the chart canvas
    var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for item in labels %}
                "{{item}}",
                {% endfor %}],
        datasets: [{
            label: '{{ legend }}',
            data: [{% for item in values %}
            {{item}},
            {% endfor %}],
            backgroundColor: [
                'rgba(5, 171, 154, 0.5)',
                'rgba(255, 99, 132, 0.5)'
            ],
            borderColor: [
                'rgba(5, 171, 154, 1)',
                'rgba(255, 99, 132, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
        yAxes: [{
            ticks: {
                beginAtZero: true
            }
        }]
    }
    }
});
</script>
{% endblock %}

app/templates/datareview.html
{% extends "template.html" %}
{% block content %}
<div class="container pt-4">
    <div class="container-fluid">
        <div id="frame_container" class="row pd-3">
            <div class="col-4">
                <center>
                    <!-- <canvas id="myChart" width="400" height="400"></canvas> -->
                    <canvas id="densityChart" width="400" height="400"></canvas>
                </center>
            </div>
            <div class="col-8">
                <center>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </center>
            </div>
        </div>
        <!-- <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div> -->
        <hr>
        <div class="row mb-3">
            <p class="d-flex mx-auto lead" style="color: #031b19;"><strong>please, stay safe and wear a mask ❤</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $('#live').attr('class', 'nav-item');
        $('#data-review').attr('class', 'nav-item active');
    })
    // Global parameters:
    // do not resize the chart canvas when its container does (keep at 600x400px)
    Chart.defaults.global.responsive = false;
    // get chart canvas
    // var ctx = document.getElementById("myChart").getContext("2d");
    var densityCanvas = document.getElementById("densityChart");

    var maskData = {
    label: 'With Mask',
    data: [{{ values }}],
    backgroundColor: 'rgba(5, 171, 154, 0.5)',
    borderColor: 'rgba(5, 171, 154, 1)',
    borderWidth: 1
    };

    var noMaskData = {
    label: 'No Mask',
    data: [{{ valuesNoMask }}],
    backgroundColor: 'rgba(255, 0, 77, 0.6)',
    borderColor: 'rgba(255, 0, 77, 1)',
    borderWidth: 1
    };

    var planetData = {
    labels: ["Today"],
    datasets: [maskData, noMaskData]
    };

    var chartOptions = {
    scales: {
        yAxes: [{
        display: true,
        scaleLabel: {
            labelString: 'Today',
            fontSize: 16 ,
            display: true
      },
        ticks: {
                beginAtZero: true
            }
        }]
    },
    legend: {
            display: true
         }
    };

    var barChart = new Chart(densityCanvas, {
    type: 'bar',
    data: planetData,
    options: chartOptions
    });


var canvas = document.getElementById("myChart");
var ctx = canvas.getContext('2d');

// Global Options:
Chart.defaults.global.defaultFontColor = 'black';
Chart.defaults.global.defaultFontSize = 16;

var data = {
  labels: [{% for item in labels2 %}
"{{item}}",
{% endfor %}],
  datasets: [{
      label: "Mask",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "rgba(5, 171, 154, 0.5)",
      borderColor: "rgba(5, 171, 154, 1)", // The main line color
      borderCapStyle: 'square',
      borderDash: [], // try [5, 15] for instance
      borderDashOffset: 0.0,
      borderJoinStyle: 'miter',
      pointBorderColor: "rgba(5, 171, 154, 1)",
      pointBackgroundColor: "rgba(5, 171, 154, 0.5)",
      pointBorderWidth: 1,
      pointHoverRadius: 8,
      pointHoverBackgroundColor: "rgba(5, 171, 154, 0.5)",
      pointHoverBorderColor: "rgba(5, 171, 154, 1)",
      pointHoverBorderWidth: 1,
      pointRadius: 4,
      pointHitRadius: 10,
      borderWidth: 1,
      // notice the gap in the data and the spanGaps: true
      data: [{% for item in values2 %}
            {{item}},
            {% endfor %}],
      spanGaps: true,
    }, {
      label: "No Mask",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "rgba(255, 0, 77, 0.6)",
      borderColor: "rgba(255, 0, 77, 1)",
      borderCapStyle: 'butt',
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: 'miter',
      pointBorderColor: "rgba(255, 0, 77, 1)",
      pointBackgroundColor: "rgba(255, 0, 77, 0.6)",
      pointBorderWidth: 1,
      pointHoverRadius: 8,
      pointHoverBackgroundColor: "rgba(255, 0, 77, 0.6)",
      pointHoverBorderColor: "rgba(255, 0, 77, 1)",
      pointHoverBorderWidth: 1,
      pointRadius: 4,
      pointHitRadius: 10,
      borderWidth: 1,
      // notice the gap in the data and the spanGaps: false
      data: [{% for item in values3 %}
            {{item}},
            {% endfor %}],
      spanGaps: false,
    }

  ]
};

// Notice the scaleLabel at the same level as Ticks
var options = {
  scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                },
                scaleLabel: {
                     display: true,
                     labelString: 'All Day',
                     fontSize: 16 
                  }
            }]            
        }  
};

// Chart declaration:
var myBarChart = new Chart(ctx, {
  type: 'line',
  data: data,
  options: options
});

</script>
{% endblock %}

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}
{% block content %}
<div class="container pt-4">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <div hidden="true" id="counter"></div>
                <img id="img1" src="/static/images/live2.png"
                     class="img-thumbnail img-fluid mx-auto d-block" style="border: 4px solid rgb(17, 153, 142); /* Gray border */
                     border-radius: 4px;  /* Rounded border */
                     padding: 5px; /* Some padding */">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div>
        <hr>
        <div class="row mb-5">
            <p class="d-flex mx-auto lead" style="color: #031b19;"><strong>please, stay safe and wear a mask ❤</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $('#data-review').attr('class', 'nav-item');
        $('#live').attr('class', 'nav-item active');
        document.querySelector("#counter").innerText = "2";
    })
    function stop(){
        $("#img1").attr("src", "/static/images/live2.png");
        $("#stop").attr("class","btn btn-danger active");
        $("#start").attr("class","btn btn-outline-success");
        document.querySelector("#counter").innerText = "2";
    }
    
    function start(){
        $("#img1").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class","btn btn-success active");
        $("#stop").attr("class","btn btn-outline-danger");
        document.querySelector("#counter").innerText = "0";
    }
    var eventSource = new EventSource("/listen")
    var waitings = false;
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    eventSource.addEventListener("message", function(e) {
      console.log(e.data)
    }, true)

    eventSource.addEventListener("online", function(e) {
      // console.log(e.data.color)
      var checkStop = document.querySelector("#counter").innerText;
      console.log(checkStop);
      if (checkStop == "2")
      {
          data.counter = "0";
      }
      else{
        data = JSON.parse(e.data)
        document.querySelector("#counter").innerText = data.counter
        document.querySelector("body").style.backgroundColor= data.color
      }
      if (data.counter == "1"){
        toastr.warning('No Mask Detected !');
        // toastr.warning('asdasd <img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:50px;">', 'Toast Image');
        // toastr.info('<img src="https://image.flaticon.com/icons/svg/34/34579.svg" style="width:150px;">', 'Toast Image')
      }
      else{
        // sleep(5000).then(() => { toastr.clear(); });
        console.log('pakai masker');
      }
    }, true)
</script>
<script>
    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-right",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "100",
        "hideDuration": "1000",
        "timeOut": "5000",
        "maxOpened": "1",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>
{% endblock %}

app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Try the mask detector on custom images</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/mask.jpg" id="image-preview" style="max-width:600px"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <h4>What is this?</h4>
        </div>
        <div class="row">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people in images and
                write a bounding box around faces, looking if they were masks or not. This is not for security
                purpose.</p>
            <p>If you are interested in more details, check this post I wrote!</p>
        </div>
        <div class="row">
            <h4>Who I am</h4>
        </div>
        <div class="row mb-5">
            <p>I'm Galileo Parise, data scientist and matematician, and I've developed what you see during Italy's
                second lockdown in November, in which I had lots of free time. If you are interested in this and ohter
                stories,
                you can follow me on Linkedin and on Medium.
                Hoping to get soon over this situation,
                I hope you all good health:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>please, stay safe and wear a mask</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled",false);
};
$(document).ready(function(){
    $('#live').attr('class', 'nav-item');
    $('#image-detector').attr('class', 'nav-item active');
})
$(function() {
        $("#submit").each(function(index){
            $(this).on('click', function(e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
            $('#image-form').serializeArray().forEach(
                function(item, index) {
                    formData.append(item.name, item.value);
                }
            );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url:  url +'',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function(response){
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>

{% endblock %}